# -*- coding: utf-8 -*-
"""AutoContent-AI-NguyenBlog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKVCMLi0RoctwcDAG5u39IE6HHSCpezt
"""

# Cài đặt thư viện
!pip install python-telegram-bot nest_asyncio PyMuPDF pytesseract Pillow python-docx openai

# Import
import nest_asyncio
nest_asyncio.apply()

from telegram import Update
from telegram.ext import ApplicationBuilder, MessageHandler, filters, ContextTypes, CommandHandler, ConversationHandler
import fitz  # PyMuPDF
import pytesseract
from PIL import Image
import io
from docx import Document
from openai import OpenAI
import os

# Thêm OpenAI API Key
client = OpenAI(api_key="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")

TOKEN = '7604536464:AAEAs7WZG0PvoBbdojFC_agY-QX1oTAzp_I'

# Định nghĩa trạng thái cho ConversationHandler
AWAITING_PROMPT = 1

# Dictionary lưu trữ văn bản của từng người dùng
user_text_data = {}

async def query_openai(prompt, text):
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            store=True,
            messages=[
                {"role": "system", "content": prompt},
                {"role": "user", "content": text}
            ],
            max_tokens=1000  # Giới hạn phản hồi tối đa 1000 tokens (~3000-4000 ký tự)
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"⚠️ Lỗi khi gọi API OpenAI: {str(e)}"

async def handle_file(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        file = await update.message.document.get_file()
        file_path = f"./{update.message.document.file_name}"

        # Tải file về máy chủ (Google Colab)
        await file.download_to_drive(file_path)
        await update.message.reply_text("✅ Đã nhận file, đang xử lý...")

        full_text = ""

        if file_path.lower().endswith(".pdf"):
            # Xử lý file PDF để lấy toàn bộ text
            pdf = fitz.open(file_path)
            for page_num in range(len(pdf)):
                page = pdf.load_page(page_num)
                text = page.get_text()
                if text.strip():
                    full_text += text
                else:
                    # Xử lý trang PDF dạng ảnh
                    pix = page.get_pixmap()
                    img_bytes = pix.tobytes()
                    img = Image.open(io.BytesIO(img_bytes))
                    ocr_text = pytesseract.image_to_string(img, lang="eng+vie")
                    full_text += ocr_text
            pdf.close()

        elif file_path.lower().endswith(".docx"):
            # Xử lý file Word
            doc = Document(file_path)
            full_text = '\n'.join([para.text for para in doc.paragraphs])

        else:
            await update.message.reply_text("⚠️ Định dạng file không được hỗ trợ.")
            return

        # Lưu văn bản để chờ prompt từ người dùng
        user_text_data[update.message.chat_id] = full_text
        await update.message.reply_text("📌 Vui lòng nhập prompt để xử lý nội dung văn bản.")
        return AWAITING_PROMPT

    except Exception as e:
        await update.message.reply_text(f"⚠️ Đã xảy ra lỗi trong quá trình xử lý: {str(e)}")

async def handle_prompt(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.message.chat_id
    if user_id not in user_text_data:
        await update.message.reply_text("⚠️ Không tìm thấy nội dung văn bản. Vui lòng gửi lại file trước.")
        return ConversationHandler.END

    prompt = update.message.text
    full_text = user_text_data.pop(user_id)  # Lấy nội dung và xóa khỏi bộ nhớ

    await update.message.reply_text("🤖 Đang gửi nội dung đến ChatGPT...")
    ai_response = await query_openai(prompt, full_text)

    # Tạo file TXT để gửi ngược lại Telegram
    response_file_path = f"response_{user_id}.txt"
    with open(response_file_path, "w", encoding="utf-8") as file:
        file.write(ai_response)

    # Gửi file TXT đến người dùng
    with open(response_file_path, "rb") as file:
        await update.message.reply_document(file)

    return ConversationHandler.END

async def main():
    app = ApplicationBuilder().token(TOKEN).build()

    conv_handler = ConversationHandler(
        entry_points=[MessageHandler(filters.Document.PDF | filters.Document.DOCX, handle_file)],
        states={
            AWAITING_PROMPT: [MessageHandler(filters.TEXT & ~filters.COMMAND, handle_prompt)]
        },
        fallbacks=[]
    )

    app.add_handler(conv_handler)

    print("🤖 Bot đang chạy...")
    await app.run_polling()

import asyncio
asyncio.run(main())



!apt-get update -y
!apt-get install tesseract-ocr -y
!apt-get install tesseract-ocr-vie -y
!apt-get install libtesseract-dev -y

!which tesseract
!tesseract --version